version: '3.2'

services:

  stiflers_mom_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: stiflers_mom
    environment:
      # use in code
      # - DEBUG=True
      # - PYTHONUNBUFFERED=1
      - SETTINGS_FILE=api.dev.yml
      # - TOKEN=SOMETOKEN #put your token in stiflers_mom\.env file

    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres
    ports:
      - 8080:8080

    #command: make adev               #dev
    command: python3 -m stiflers_mom #prod

    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  postgres:
    image: postgres:10
    container_name: stiflers_mom_postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
        - 5433:5432
    restart: always
    volumes:
        - ./db_dev:/var/lib/postgresql/data  

    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  # test:
  #   <<: *app
  #   container_name: stiflers_mom_test
  #   ports:
  #     - 8082:8082
  #   command: make _test
