"""empty message

Revision ID: ddd04fcbcbf6
Revises: 
Create Date: 2019-08-22 13:07:52.196511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddd04fcbcbf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macs_captured',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('snifid', sa.String(length=12), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=True),
    sa.Column('frames_with_fine_rssi', sa.Integer(), nullable=True),
    sa.Column('frames_count', sa.Integer(), nullable=True),
    sa.Column('rssi_max', sa.Integer(), nullable=True),
    sa.Column('rssi_avg', sa.Integer(), nullable=True),
    sa.Column('notified_count', sa.Integer(), nullable=True),
    sa.Column('known_from', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macs_captured_id'), 'macs_captured', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('gender', postgresql.ENUM('women', 'male', 'none', name='usergender'), server_default='none', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_macs_captured_id'), table_name='macs_captured')
    op.drop_table('macs_captured')
    # ### end Alembic commands ###
