"""empty message

Revision ID: 0466bdc0e35e
Revises: 783f0f0942c4
Create Date: 2019-08-20 16:19:23.335031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0466bdc0e35e'
down_revision = '783f0f0942c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macs_captured', sa.Column('known_from', sa.Integer(), nullable=True))
    op.drop_column('macs_captured', 'first_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macs_captured', sa.Column('first_timestamp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('macs_captured', 'known_from')
    # ### end Alembic commands ###
