"""empty message

Revision ID: 13e7c4d844c5
Revises: b85b7b62cb17
Create Date: 2019-08-22 10:06:59.632157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e7c4d844c5'
down_revision = 'b85b7b62cb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
