"""empty message

Revision ID: 3614b2491b49
Revises: 13e7c4d844c5
Create Date: 2019-08-22 10:07:47.184005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3614b2491b49'
down_revision = '13e7c4d844c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macs_captured', sa.Column('frames_with_fine_rssi', sa.Integer(), nullable=True))
    op.drop_column('macs_captured', 'frames_with_rssi_max')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macs_captured', sa.Column('frames_with_rssi_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('macs_captured', 'frames_with_fine_rssi')
    # ### end Alembic commands ###
