"""empty message

Revision ID: 68a77becabd1
Revises: 50f72f926b0e
Create Date: 2019-08-20 15:11:35.993870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a77becabd1'
down_revision = '50f72f926b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
