"""empty message

Revision ID: 783f0f0942c4
Revises: ee36aa9a07db
Create Date: 2019-08-20 15:43:47.254382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783f0f0942c4'
down_revision = 'ee36aa9a07db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macs_captured', sa.Column('first_timestamp', sa.Integer(), nullable=True))
    op.add_column('macs_captured', sa.Column('notified_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('macs_captured', 'notified_count')
    op.drop_column('macs_captured', 'first_timestamp')
    # ### end Alembic commands ###
