"""empty message

Revision ID: b85b7b62cb17
Revises: 0466bdc0e35e
Create Date: 2019-08-21 14:00:15.083590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85b7b62cb17'
down_revision = '0466bdc0e35e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
