"""empty message

Revision ID: ee36aa9a07db
Revises: 68a77becabd1
Create Date: 2019-08-20 15:16:23.032753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee36aa9a07db'
down_revision = '68a77becabd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macs_captured',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('snifid', sa.String(length=12), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('vendor', sa.Text(), nullable=True),
    sa.Column('frames_with_rssi_max', sa.Integer(), nullable=True),
    sa.Column('frames_count', sa.Integer(), nullable=True),
    sa.Column('rssi_max', sa.Integer(), nullable=True),
    sa.Column('rssi_avg', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macs_captured_id'), 'macs_captured', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macs_captured_id'), table_name='macs_captured')
    op.drop_table('macs_captured')
    # ### end Alembic commands ###
