# app
app:
  host: 0.0.0.0
  port: 8080

# postgres
postgres:
  user: postgres
  password: postgres
  database: postgres
  port: 5432
  host: postgres


clickhouse:
  user: default
  password: smartwifi
  database: default
  url: http://snif-db.dev.enforta.net:8123
  compress_response: True


bigdata:
  url: https://46b4477f329048829f0ec979cb629e02.domru.ru/raw